name: "Labels: Review (Backend)"

on:
  workflow_run:
    workflows: ["Labels: Approval"]
    types: [completed]

jobs:
  # Apply the label to the PR, only if it's a PR from a fork
  apply-review-backend:
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_repository.full_name != github.repository
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      actions: write
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Run Apply Label Action
        uses: ./.github/actions/apply-label
        id: applylabel

      - name: Remove Old Label
        continue-on-error: true
        env:
          PR_NO: github.steps.applylabel.pr_num
          OLD_LABEL: "S: Needs Review"
        run: 'gh pr edit "$PR_NO" --repo "${{ github.repository }}" --remove-label "$OLD_LABEL"'
