name: "Labels: Review (Backend)"

on:
  workflow_run:
    workflows: ["Labels: Approval"]
    types: [completed]

jobs:
  apply-and-clean:
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      actions: write
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Run Hidden Label Action
        uses: ./.github/actions/apply-label
