name: "Labels: Approval"

on:
  pull_request_review:
    types: [submitted]

jobs:
  detect-approval:
    if: github.event.review.state == 'approved' && github.event.pull_request.head.repo.full_name != github.repository
    runs-on: ubuntu-latest
    env:
      LABEL: "S: Approval"
    steps:
      - name: Save PR context
        run: |
          mkdir -p ./pr
          echo "${{ github.event.pull_request.number }}" > ./pr/NR
          echo "$LABEL" > ./pr/LABEL
      
      - name: Upload PR number
        uses: actions/upload-artifact@v4
        with:
          name: pr-approval-${{ github.run_id }}
          path: pr/
          retention-days: 1
